apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-soap-backend
  labels:
    app: telecom-soap-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telecom-soap-backend
  template:
    metadata:
      labels:
        app: telecom-soap-backend
    spec:
      containers:
        - name: soap-backend
          image: rakeshdocker7/telecom-soap-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "8090"
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
